### PR TITLE
Create coding standards

### PR DESCRIPTION
**Pull request by adamgayoso**
I believe we should conform to a coding style. 

- Proposed use of the black formatter and flake8 linter (using the settings from black)

- Added pre-commit hooks (via pre-commit package) so that we do not commit non-compliant code

- Added .editorconfig file, which vscode will use to override settings for this project

https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

- Added CONTRIBUTING.rst for explanation of how to contribute

VS Code will also recognize the setup.cfg file to override default flake8 args.

### CODE REVIEW

**Comment by adamgayoso** [comment]
@JonathanShor Feel free to change any of the settings

**Comment by adamgayoso** [comment]
I have chosen not to use black on the codebase in this PR as we will be merging this along with the 3.0 release.

**Comment by JonathanShor** [comment]
You know I am in favor of most of this, but I'm not sure it actually needs to be part of the repo. This is all development stuff. Who else do you envision is developing this package beyond us?
That's the most important thing to establish before I can assess the particulars.

Tho, also talk to me about `max-line-length = 119`.

**Comment by adamgayoso** [comment]
I think this is beneficial even to just us as it's the easiest way to share this kind of information. Having these settings in your vs code Workspace is fine, but this is even easier because you don't have to think about it. If we take another hiatus, at least when we come back we won't have to remember our editor settings (assuming new computer, etc.).

**Comment by adamgayoso** [comment]
We can change the max line length to whatever you want.

**Pull request merged**
